using DoubleLinkedList;

var a = new DoubleLinkedList<int>();
a.Add(2);
a.Add(12);
a.Add(32);
a.Add(42);
a.Remove(32);
a.Add(67);
a.Remove(2);
a.InsertAt(3, 0);
a.InsertAt(345, 0);
a.InsertAt(345, 5);
a.Remove(67);
a.Add(56);
a.Remove(3);
a.InsertAt(4, 5);
a.Remove(56);
a.Remove(345);
a.Remove(345);
a.RemoveAt(1);
var ar = new int[] { 1, 2, 3, 4, 5, 6,7,8,9 };
a.CopyTo(ar, 3);
Console.WriteLine(string.Join(", ",ar));
a.AddRange(new int[] { 10 });
a.RemoveAt(0);
Console.WriteLine(a.Contains(4));
Console.WriteLine(a.Contains(10));
a.Reverse();
a.PrintReverse();
a.Print();